<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260912095407 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Suppliers, properties, imports, offers and reservations';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE imports (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, external_import_id VARCHAR(100) NOT NULL, status VARCHAR(20) NOT NULL, sent_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, payload JSONB NOT NULL, total_offers INT NOT NULL, processed_offers INT NOT NULL, error TEXT DEFAULT NULL, completed_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, supplier_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_imports_supplier_external_id ON imports (supplier_id, external_import_id)');
        $this->addSql('CREATE INDEX IDX_7895ED1C2ADD6D8C ON imports (supplier_id)');
        $this->addSql('CREATE TABLE offers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, external_id VARCHAR(100) NOT NULL, check_in DATE NOT NULL, check_out DATE NOT NULL, max_guests SMALLINT NOT NULL, price INT NOT NULL, currency CHAR(3) NOT NULL, available_units INT NOT NULL, expires_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, supplier_id INT NOT NULL, property_id INT NOT NULL, import_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_offers_search ON offers (check_in, check_out, max_guests, price)');
        $this->addSql('CREATE INDEX idx_offers_property_price ON offers (property_id, price)');
        $this->addSql('CREATE UNIQUE INDEX uniq_offers_supplier_external_id ON offers (supplier_id, external_id)');
        $this->addSql('CREATE INDEX IDX_DA4604272ADD6D8C ON offers (supplier_id)');
        $this->addSql('CREATE INDEX IDX_DA460427549213EC ON offers (property_id)');
        $this->addSql('CREATE INDEX IDX_DA460427B6A263D9 ON offers (import_id)');
        $this->addSql('CREATE TABLE properties (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(100) NOT NULL, name VARCHAR(255) NOT NULL, city VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_properties_city ON properties (city)');
        $this->addSql('CREATE UNIQUE INDEX uniq_properties_code ON properties (code)');
        $this->addSql('CREATE TABLE reservations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, client_reference VARCHAR(100) NOT NULL, customer_name VARCHAR(255) NOT NULL, customer_email VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, offer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_reservations_offer_client_reference ON reservations (offer_id, client_reference)');
        $this->addSql('CREATE INDEX IDX_4DA23953C674EE ON reservations (offer_id)');
        $this->addSql('CREATE TABLE suppliers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_suppliers_code ON suppliers (code)');
        $this->addSql('ALTER TABLE imports ADD CONSTRAINT FK_7895ED1C2ADD6D8C FOREIGN KEY (supplier_id) REFERENCES suppliers (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE offers ADD CONSTRAINT FK_DA4604272ADD6D8C FOREIGN KEY (supplier_id) REFERENCES suppliers (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE offers ADD CONSTRAINT FK_DA460427549213EC FOREIGN KEY (property_id) REFERENCES properties (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE offers ADD CONSTRAINT FK_DA460427B6A263D9 FOREIGN KEY (import_id) REFERENCES imports (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservations ADD CONSTRAINT FK_4DA23953C674EE FOREIGN KEY (offer_id) REFERENCES offers (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE imports DROP CONSTRAINT FK_7895ED1C2ADD6D8C');
        $this->addSql('ALTER TABLE offers DROP CONSTRAINT FK_DA4604272ADD6D8C');
        $this->addSql('ALTER TABLE offers DROP CONSTRAINT FK_DA460427549213EC');
        $this->addSql('ALTER TABLE offers DROP CONSTRAINT FK_DA460427B6A263D9');
        $this->addSql('ALTER TABLE reservations DROP CONSTRAINT FK_4DA23953C674EE');
        $this->addSql('DROP TABLE imports');
        $this->addSql('DROP TABLE offers');
        $this->addSql('DROP TABLE properties');
        $this->addSql('DROP TABLE reservations');
        $this->addSql('DROP TABLE suppliers');
    }
}
